### PR TITLE
Create speria846

### PR DESCRIPTION
**Pull request by speria846**

### CODE REVIEW

**Comment by Florencekyarikunda** [comment]
Hi Speriah,
Make sure they will not get you forking or deploying the code from my
github. When they get you, bambi you will be mistreated their.

**Comment by Florencekyarikunda** [comment]
This is the screen shot i have found

**Comment by speria846** [comment]
do they look at this and know that this is yours

**Comment by Florencekyarikunda** [comment]
yes they will know

**Comment by speria846** [comment]
just the screenshot

**Comment by speria846** [comment]
please tell because i submitted it in pip yesterday.i copied the code to my
visual studio and screenshot it like this,that  i researched and did it.

**Comment by Florencekyarikunda** [comment]
ignore the first one

**Comment by Florencekyarikunda** [comment]
i don't know how to do it

**Pull request closed without merging**
